#!/usr/bin/env python3
"""Glue between Stage A's real output and Stage B's orchestrator.

Reads Stage A's combined store.jsonl (driver.py's output) and produces the two
input files stage_b_orchestrator.py expects:

  - notes_batch.jsonl  -- every module record, in real dependency-safe order
    (official modules first per Operator's requirement, each group in the real
    topological order from odoo_full_module_graph.json) so that
    GraphStore.bounded_context_for() sees each module's dependencies' notes
    already generated by the time it's that module's turn, within one run.
  - review_batch.jsonl -- every needs_llm_review item, flattened out of its
    parent module record with a "module" key added (Stage A stores them
    nested; Stage B's review batch format expects them flat).

No LLM calls, no network access, no real source content beyond what Stage A
already parsed and wrote to disk locally.

Usage:
    python3 build_stage_b_batches.py <stage_a_store_jsonl> <output_dir>
"""

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent))

from paths import KNOWLEDGE_GRAPH_DATA_PATH  # noqa: E402

GRAPH_JSON_PATH = KNOWLEDGE_GRAPH_DATA_PATH / "odoo_full_module_graph.json"


def real_module_order() -> list[str]:
    data = json.loads(GRAPH_JSON_PATH.read_text())
    modules = data["modules"]
    topo_position = {name: i for i, name in enumerate(data["topo_order"])}
    official = sorted((n for n in modules if modules[n].get("is_official")), key=lambda n: topo_position[n])
    third_party = sorted((n for n in modules if not modules[n].get("is_official")), key=lambda n: topo_position[n])
    return official + third_party


def main() -> int:
    if len(sys.argv) != 3:
        print(__doc__)
        return 1

    store_path = Path(sys.argv[1])
    out_dir = Path(sys.argv[2])
    out_dir.mkdir(parents=True, exist_ok=True)

    records_by_module = {}
    with store_path.open() as f:
        for line in f:
            line = line.strip()
            if line:
                rec = json.loads(line)
                records_by_module[rec["module"]] = rec

    order = [m for m in real_module_order() if m in records_by_module]
    missing = [m for m in real_module_order() if m not in records_by_module]

    notes_path = out_dir / "notes_batch.jsonl"
    with notes_path.open("w") as f:
        for module in order:
            f.write(json.dumps(records_by_module[module]))
            f.write("\n")

    review_items = []
    for module in order:
        rec = records_by_module[module]
        for item in rec.get("needs_llm_review", []):
            review_items.append({
                "module": module,
                "model": item.get("model"),
                "reason": item["reason"],
                "snippet": item["snippet"],
                # self-reference: lets build_review_prompt pull in this module's own
                # already-known facts (fields already resolved on the same model, DEPS,
                # etc.) from the graph -- real context that was available but unused.
                "references": [module],
            })

    review_path = out_dir / "review_batch.jsonl"
    with review_path.open("w") as f:
        for item in review_items:
            f.write(json.dumps(item))
            f.write("\n")

    print(f"notes_batch.jsonl: {len(order)} modules -> {notes_path}")
    print(f"review_batch.jsonl: {len(review_items)} items -> {review_path}")
    if missing:
        print(f"({len(missing)} modules in the real graph have no Stage A record yet: {missing})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
